### ISSUE TITLE
apk releases

### ISSUE THREAD

**Issue by nascentt** [williscool/CalendarNotification#23]
Firstly, thank you for forking and working on this,  this is the best productivity app ever and i was sad to see the original repo marked read only.
I use Obtainium to install and auto update non-play store apps, which works with github and fdroid.

Sadly I cannot find a fdroid release of this fork, anf the github page has no apk releases so Obtainium cannot install from here.

It'd be much appreciated if you could add apk releases either here or f-droid.

**Comment by williscool** [comment]
Hi @nascentt ! thanks for the kind words! 

I dont have a lot of bandwith to work on the application but would happily accept a good PR!

I've already got workflows setup that build apks for each pull request to make sure everything is working


https://github.com/williscool/CalendarNotification/blob/master/.github/workflows/actions.yml

just need to set it up so that every pull request merged to master creates 

https://github.com/williscool/CalendarNotification/releases

apks!

I may be able to get to that next time im working on this but could be a while!

**Comment by bentolor** [comment]
Same here: Really missing this app after phone upgrade and Android 11 to 14: I no longer get any notifications. So thanks for your efforts to resurrect CalendarNotification.

Above you mentioned that mostly you'd miss an automatic APK creation for the mainline. My question is: What's the status of this fork over the archived upstream version? Would it help me to get it run on Android 14 again, @williscool ?  

Looking at the the issues most of them seem to address the development and some feature requests. My interest would be to get the functionality at least running again as it is and I wonder on the state of this fork in this regard.

Again, thanks for your contributions, Williams!

**Comment by williscool** [comment]
@bentolor I'm using the app on Android 14 on a Samsung Galaxy Fold 4.

Can you open a separate issue and share as much about your device as you can?

Also as far as I know the upstream is dead. I updated this fork enough to get the backup configs updated so I could get a backup of the database out of the application for a separate app that I'm working on so that I can move things around on my calendar more easily. 

The other features I'm working on are related to making that process easier also

**Comment by williscool** [comment]
https://stackoverflow.com/q/75679683/511710

**Comment by williscool** [comment]
https://github.com/marketplace/actions/release-drafter

**Comment by williscool** [comment]
https://stackoverflow.com/questions/75164222/how-to-upload-a-release-in-github-action-using-github-script-action

**Comment by williscool** [comment]
https://github.com/marketplace/actions/android-version-bump-automatically

**Comment by williscool** [comment]
on merge I want to

1. bump the version code
2. bump the version name according to https://github.com/marketplace/actions/android-version-bump-automatically
3. make a release with the apks attached like happens with prs

**Comment by williscool** [comment]
if all goes well on https://github.com/williscool/CalendarNotification/actions/runs/11047599762

you have your wish @nascentt !

**Comment by nascentt** [comment]
That'd be great!
I noticed the original calendar notifications app was deleted from fdroid in the past few days. So it'd be especially great to be able to easily download apks of this fork.

**Comment by williscool** [comment]
Release attachment works! 

https://github.com/williscool/CalendarNotification/releases/tag/v6.0.0

Feel free to comment to reopen this issue if you have trouble with the apks!

**Comment by nascentt** [comment]
Thanks so much for this
I've set up obtaining to point your your releases to maintain updates.  So far working great.
